import { StyleSheet } from 'react-native';

const gameGridStyles = StyleSheet.create({
  gameGrid: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#333',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    padding: 8,
    width: 264, // 3 * 80 + 3 * 8 (aprox)
    minWidth: 240,
    maxWidth: 300,
  },
  gridRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
  },
  gridCell: {
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: '#999',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    overflow: 'hidden',
    position: 'relative',
    margin: 2,
  },
  ingredientBackground: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 8,
    zIndex: 0,
  },
  ingredientContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  ingredientEmoji: {
    fontSize: 28,
    marginBottom: 2,
  },
  ingredientText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    textShadowColor: 'rgba(255, 255, 255, 0.9)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  playerPiece: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 4,
    right: 4,
    zIndex: 3,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    opacity: 0.9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 4,
  },
  player1Piece: {
    backgroundColor: '#8B4513',
  },
  player2Piece: {
    backgroundColor: '#32CD32',
  },
  pieceText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  selectedCell: {
    borderColor: '#FFD700',
    borderWidth: 3,
    backgroundColor: '#FFF8DC',
  },
  possibleMoveCell: {
    borderColor: '#32CD32',
    borderWidth: 3,
    backgroundColor: '#F0FFF0',
  },
  selectedPiece: {
    borderWidth: 3,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOpacity: 0.6,
  },
  overlappedPiece1: {
    right: 4,
    top: 4,
    zIndex: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  overlappedPiece2: {
    left: 4,
    bottom: 4,
    top: 'auto',
    right: 'auto',
    zIndex: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  possibleMoveIndicator: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#32CD32',
    opacity: 0.7,
    bottom: 4,
    right: 4,
    zIndex: 4,
  },
  pickupEffect: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  pickupText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6F4E37',
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
});

export default gameGridStyles;
